# -*- coding: utf-8 -*-
"""
N body simulator

Author: Eryn Cangi
For CIERA REU summer 2015

Heavily lifted from http://fiftyexamples.readthedocs.org/en/latest/gravity.html
License is MIT license, free to use and modify as desired for any use
"""

import turtle as t
import numpy as np
from math import sin, cos
    
class Body(t.Turtle):
    '''
    Defines a body object and its attributes, i.e. a planet, satellite, etc.
    Inherits from Turtle for easy drawing
    '''

    def __init__(self, name, mass, color, pos, vel):
        self.name = name
        self.mass = mass
        self.pencolor = color
        self.position = pos                         # numpy array            
        self.velocity = vel                         #

    def __repr__(self):
        return '{name} at {pos} with speed {vel}, mass {mass}'\
        .format(name = self.name, pos = self.position, vel = self.velocity, 
                mass = self.mass)
        
    def force(self, other):
        '''
        Calculates force between the object and another one
        '''
        
        G = 6.67384 * 10**(-11)

        if self is other:
            raise ValueError("Can't attract object to itself")

        # calculate distance
        # can possibly improve per: http://bit.ly/1I6rLjj
        dr = self.position - other.position         # format [dx, dy, dz]
        r = np.linalg.norm(dr) 
        
        # calculate force
        fg = (G * self.mass * other.mass) / r^2
        
        # calculate direction of force, theta = azimuthal, phi = polar
        theta = np.arctan(dr[1] / dr[0])
        phi = np.arccos(dr[2] / r)
        
        # could collapse later maybe
        gravity_x = fg * cos(theta) * sin(phi)
        gravity_y = fg * sin(theta) * sin(phi)
        gravity_z = fg * cos(phi)
        
        gravity = np.array([gravity_x, gravity_y, gravity_z])
        
        return gravity
        
        
def fill_arrays():
    '''
    Fills numpy arrays with data generated by simulation
    '''
    pass


def run(bodies, SCALE):
    '''
    Runs the main simulation
    '''
    
    timestep = 24*3600                  # start with one day as the time step
    
    for each in bodies:
        each.penup()
        each.hideturtle()
        
    force = {}                          # dictionary of forces from other bodies
    
    # Add up all of the forces exerted on 'body'.
    for body in bodies:
            
        total_fx = total_fy = total_fz = 0.0
        for other in bodies:
            # Don't calculate the body's attraction to itself
            if body is other:
                continue
            grav_vector = body.force(other)
            total_fx += grav_vector[0]
            total_fy += grav_vector[1]
            total_fz += grav_vector[2]

        # Record the total force exerted.
        force[body] = (total_fx, total_fy, total_fz)

    # Update velocities based upon on the force.
    for body in bodies:
        fx, fy, fz = force[body]
        body.velocity = (np.array([fx, fy, fz]) / body.mass) * timestep

        # Update positions and draw on canvas
        body.position = body.velocity * timestep
        body.goto(body.position[0]*SCALE, body.position[1]*SCALE)
        body.dot(3)

    pass


def main():
    '''
    Main loop
    '''  
    
    # Assumed scale: 100 pixels = 1AU.
    AU = (149.6e9)     # 149.6 billion meters.
    SCALE = 250 / AU
    
    # Declare positions and velocities for two bodies
    sun_pos = np.array([0,0,0])
    sun_vel = [0,0,0]
    earth_pos = np.array([1*AU, 0, 0])
    earth_vel = np.array([0, 3e4])              # earth = 30 km per sec
    
    sun = Body('Sun', 2e30, 'yellow', sun_pos, sun_vel), 
    earth = Body('Earth', 5.9742e24, 'blue', earth_pos, earth_vel)

    run([sun, earth], SCALE)
